### ISSUE TITLE
failed make in BNG-packaged SBMLparser

### ISSUE THREAD

**Issue by ryants** [RuleWorld/atomizer#2]
I ran 'make' in the SBMLparser directory of the BNG 2.2.6 distribution, but I get the following error:
```
Traceback (most recent call last):
  File "pyinstaller2/pyinstaller.py", line 18, in <module>
    run()
  File "/auto/nest/nest/u/ryants/tools/BioNetGen-2.2.6-stable/SBMLparser/pyinstaller2/PyInstaller/main.py", line 88, in run
    run_build(opts, spec_file, pyi_config)
  File "/auto/nest/nest/u/ryants/tools/BioNetGen-2.2.6-stable/SBMLparser/pyinstaller2/PyInstaller/main.py", line 46, in run_build
    PyInstaller.build.main(pyi_config, spec_file, **opts.__dict__)
  File "/auto/nest/nest/u/ryants/tools/BioNetGen-2.2.6-stable/SBMLparser/pyinstaller2/PyInstaller/build.py", line 1994, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/auto/nest/nest/u/ryants/tools/BioNetGen-2.2.6-stable/SBMLparser/pyinstaller2/PyInstaller/build.py", line 1940, in build
    execfile(spec)
  File "sbmlTranslator.spec", line 6, in <module>
    excludes=['PyQt4', 'PyQt4.QtCore', 'PyQt4.QtGui','matplotlib','IPython','PIL','X11','gtk','pandas','scipy'])
  File "/auto/nest/nest/u/ryants/tools/BioNetGen-2.2.6-stable/SBMLparser/pyinstaller2/PyInstaller/build.py", line 419, in __init__
    raise ValueError("script '%s' not found" % script)
ValueError: script 'SBMLparser/sbmlTranslator.py' not found
make: *** [all] Error 1
```
Again using Ubuntu 12.04 LTS

**Comment by jjtapia** [comment]
Hello. It seems that that particular distribution is missing the file. Where did you get the 2.2.6 package from?

**Comment by ryants** [comment]
I'm pretty sure I got it [here](http://www.csb.pitt.edu/Faculty/Faeder/?sdm_downloads=bionetgen-for-linux)

**Comment by jjtapia** [comment]
Apparently there was an issue during the packaging process that caused some source files to be missing from the 2.2.6 distro zip files, which caused the issue you reported. Thanks for the notice, the issue is corrected now and if you download the package you linked to again you should be able to make atomizer without issues.

That said, if you can make atomizer from the git source that would be better as I've implemented several bugfixes to the algorithm in the last 6 months.
